
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `binaryDIF`=list(
        `type`="software", 
        `author`="Friesen, L., Kroc, E., Zumbo, B. D.", 
        `year`=2019, 
        `title`="PsychoPDA: Binary Differential Item Functioning", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/lucasjfriesen/jamoviPsychoPDA", 
        `url`="https://github.com/lucasjfriesen/jamoviPsychoPDA"))
