
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `testROC`=list(
        `type`="software", 
        `author`="Friesen, L., Kroc, E., Zumbo, B. D.", 
        `year`=2019, 
        `title`="Psychometrics & Post-Data Analysis: Test ROC", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/lucasjfriesen/jamoviPsychoPDA", 
        `url`="https://github.com/lucasjfriesen/jamoviPsychoPDA"), 
    `NIRT`=list(
        `type`="software", 
        `author`="Friesen, L., Kroc, E., Zumbo, B. D.", 
        `year`=2019, 
        `title`="Psychometrics & Post-Data Analysis: Non-Parametric Item Response Theory", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/lucasjfriesen/jamoviPsychoPDA", 
        `url`="https://github.com/lucasjfriesen/jamoviPsychoPDA"), 
    `binaryDIF`=list(
        `type`="software", 
        `author`="Friesen, L., Kroc, E., Zumbo, B. D.", 
        `year`=2019, 
        `title`="Psychometrics & Post-Data Analysis: Binary Differential Item Functioning", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/lucasjfriesen/jamoviPsychoPDA", 
        `url`="https://github.com/lucasjfriesen/jamoviPsychoPDA"), 
    `gelmanCarlin2014`=list(
        `type`="paper", 
        `author`="Gelman, A., Carlin, J.", 
        `year`=2014, 
        `title`="Beyond Power Calculations: Assessing Type S (Sign) and Type M (Magnitude) Errors", 
        `publisher`="Perspectives on Psychological Science: A Journal of the Association for Psychological Science", 
        `doi`="10.1177/1745691614551642"), 
    `zumboThomas`=list(
        `type`="paper", 
        `author`="Zumbo, B. D., Thomas, R. D.", 
        `year`=1997, 
        `title`="A measure of effect size for a model-based approach for studying DIF", 
        `publisher`="Working Paper of the Edgeworth Laboratory for Quantitative Behavioral Science; University of Northern British Columbia: Prince George, B.C."), 
    `cutpointr`=list(
        `type`="paper", 
        `author`="Thiele, C.", 
        `year`=2019, 
        `title`="cutpointr: Determine and Evaluate Optimal Cutpoints in Binary Classification Tasks", 
        `publisher`="[R package]. Retrieved from  https://cran.r-project.org/package=cutpointr"))
