
# This file is automatically generated, you probably don't want to edit this

glmDIFOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "glmDIFOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            item = NULL,
            group = NULL,
            matchVar = NULL,
            anchor = NULL,
            focal = NULL,
            groupType = NULL,
            difFlagScale = NULL,
            designAnalysis = FALSE,
            designAnalysisSigOnly = TRUE,
            power = FALSE,
            D = NULL,
            sims = 5000,
            type = "both",
            criterion = NULL,
            alpha = 0.05,
            purify = FALSE,
            nIter = 10,
            pAdjustMethod = "BH",
            plotVarsICC = NULL, ...) {

            super$initialize(
                package='DIF',
                name='glmDIF',
                requiresData=TRUE,
                ...)

            private$..item <- jmvcore::OptionVariables$new(
                "item",
                item,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..matchVar <- jmvcore::OptionVariable$new(
                "matchVar",
                matchVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..anchor <- jmvcore::OptionVariables$new(
                "anchor",
                anchor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..focal <- jmvcore::OptionString$new(
                "focal",
                focal)
            private$..groupType <- jmvcore::OptionList$new(
                "groupType",
                groupType,
                options=list(
                    "group",
                    "cont"))
            private$..difFlagScale <- jmvcore::OptionList$new(
                "difFlagScale",
                difFlagScale,
                options=list(
                    "zt",
                    "jg"))
            private$..designAnalysis <- jmvcore::OptionBool$new(
                "designAnalysis",
                designAnalysis,
                default=FALSE)
            private$..designAnalysisSigOnly <- jmvcore::OptionBool$new(
                "designAnalysisSigOnly",
                designAnalysisSigOnly,
                default=TRUE)
            private$..power <- jmvcore::OptionBool$new(
                "power",
                power,
                default=FALSE)
            private$..D <- jmvcore::OptionNumber$new(
                "D",
                D)
            private$..sims <- jmvcore::OptionNumber$new(
                "sims",
                sims,
                default=5000)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "udif",
                    "nudif",
                    "both"),
                default="both")
            private$..criterion <- jmvcore::OptionList$new(
                "criterion",
                criterion,
                options=list(
                    "Wald",
                    "LRT"))
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..purify <- jmvcore::OptionBool$new(
                "purify",
                purify,
                default=FALSE)
            private$..nIter <- jmvcore::OptionNumber$new(
                "nIter",
                nIter,
                default=10)
            private$..pAdjustMethod <- jmvcore::OptionList$new(
                "pAdjustMethod",
                pAdjustMethod,
                options=list(
                    "bonferroni",
                    "holm",
                    "hochberg",
                    "hommel",
                    "BH",
                    "BY",
                    "none"),
                default="BH")
            private$..plotVarsICC <- jmvcore::OptionVariables$new(
                "plotVarsICC",
                plotVarsICC)

            self$.addOption(private$..item)
            self$.addOption(private$..group)
            self$.addOption(private$..matchVar)
            self$.addOption(private$..anchor)
            self$.addOption(private$..focal)
            self$.addOption(private$..groupType)
            self$.addOption(private$..difFlagScale)
            self$.addOption(private$..designAnalysis)
            self$.addOption(private$..designAnalysisSigOnly)
            self$.addOption(private$..power)
            self$.addOption(private$..D)
            self$.addOption(private$..sims)
            self$.addOption(private$..type)
            self$.addOption(private$..criterion)
            self$.addOption(private$..alpha)
            self$.addOption(private$..purify)
            self$.addOption(private$..nIter)
            self$.addOption(private$..pAdjustMethod)
            self$.addOption(private$..plotVarsICC)
        }),
    active = list(
        item = function() private$..item$value,
        group = function() private$..group$value,
        matchVar = function() private$..matchVar$value,
        anchor = function() private$..anchor$value,
        focal = function() private$..focal$value,
        groupType = function() private$..groupType$value,
        difFlagScale = function() private$..difFlagScale$value,
        designAnalysis = function() private$..designAnalysis$value,
        designAnalysisSigOnly = function() private$..designAnalysisSigOnly$value,
        power = function() private$..power$value,
        D = function() private$..D$value,
        sims = function() private$..sims$value,
        type = function() private$..type$value,
        criterion = function() private$..criterion$value,
        alpha = function() private$..alpha$value,
        purify = function() private$..purify$value,
        nIter = function() private$..nIter$value,
        pAdjustMethod = function() private$..pAdjustMethod$value,
        plotVarsICC = function() private$..plotVarsICC$value),
    private = list(
        ..item = NA,
        ..group = NA,
        ..matchVar = NA,
        ..anchor = NA,
        ..focal = NA,
        ..groupType = NA,
        ..difFlagScale = NA,
        ..designAnalysis = NA,
        ..designAnalysisSigOnly = NA,
        ..power = NA,
        ..D = NA,
        ..sims = NA,
        ..type = NA,
        ..criterion = NA,
        ..alpha = NA,
        ..purify = NA,
        ..nIter = NA,
        ..pAdjustMethod = NA,
        ..plotVarsICC = NA)
)

glmDIFResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        instructions = function() private$.items[["instructions"]],
        DESCtable = function() private$.items[["DESCtable"]],
        DIFtable = function() private$.items[["DIFtable"]],
        gcTable = function() private$.items[["gcTable"]],
        ICCplots = function() private$.items[["ICCplots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Differential Item Functioning")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                title="debug"))
            self$add(jmvcore::Table$new(
                options=options,
                name="instructions",
                title="Instructions",
                rows=4,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="ted", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="DESCtable",
                title="Procedure Notes",
                rows=0,
                columns=list(
                    list(
                        `name`="bob", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="DIFtable",
                title="Differential Item Functioning Analysis",
                rows="(item)",
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="P-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="effSize", 
                        `title`="Naeglekirke R^2", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="difType", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="ZT", 
                        `title`="Zumbo-Thomas", 
                        `type`="text", 
                        `visible`="(difFlagScale:zt)"),
                    list(
                        `name`="JG", 
                        `title`="Jodoin-Gierl", 
                        `type`="text", 
                        `visible`="(difFlagScale:jg)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="gcTable",
                title="Design Analysis",
                rows=0,
                visible="(designAnalysis)",
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="hypTrueEff", 
                        `title`="Hypothesized True Effect", 
                        `type`="text"),
                    list(
                        `name`="typeM", 
                        `title`="Type-M", 
                        `type`="number", 
                        `format`="pvalue"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number", 
                        `format`="(zto)", 
                        `visible`="(power)"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="ICCplots",
                title="Item Characteristic Curves",
                items="(plotVarsICC)",
                template=jmvcore::Image$new(
                    options=options,
                    width=550,
                    height=450,
                    renderFun=".plotICC",
                    visible="(plotVarsICC)",
                    requiresData=TRUE,
                    clearWith=list(
                        "item",
                        "group",
                        "matchVar",
                        "anchor",
                        "focal",
                        "groupType",
                        "type",
                        "criterion",
                        "alpha",
                        "nIter",
                        "purify"))))}))

glmDIFBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "glmDIFBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'DIF',
                name = 'glmDIF',
                version = c(1,0,0),
                options = options,
                results = glmDIFResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Differential Item Functioning
#'
#' Differential Item Functioning (DIF) analysis is used to assess items on
#' a test or measure to determine whether or not certain groups are performing
#' diferentially on that item.
#' 
#'
#' @examples
#' \dontrun{
#' data('verbal')}
#' @param data the data as a data frame
#' @param item a vector of strings naming the item columns from \code{data}
#' @param group a string naming the grouping variable from \code{data}
#' @param matchVar a string naming the matching variable from \code{data}
#' @param anchor a vector of strings naming the anchor item columns from
#'   \code{data}
#' @param focal a string indicating which group(s) are to be considered focal
#'   groups
#' @param groupType either "discrete" (default) to specify that group
#'   membership is made of two (or more than two) groups, or "continuous" to
#'   indicate that group membership is based on a continuous criterion.
#' @param difFlagScale .
#' @param designAnalysis .
#' @param designAnalysisSigOnly .
#' @param power .
#' @param D .
#' @param sims .
#' @param type a character string specifying which DIF effects must be tested.
#'   Possible values are "both" (default), "udif" and "nudif"
#' @param criterion a character string specifying which DIF statistic is
#'   computed. Possible values are "LRT" (default) or "Wald"
#' @param alpha significance level
#' @param purify should the method be used iteratively to purify the set of
#'   anchor items? (default is FALSE). Ignored if match is not "score"
#' @param nIter the maximal number of iterations in the item purification
#'   process. (default is 10)
#' @param pAdjustMethod either NULL (default) or the acronym of the method for
#'   p-value adjustment for multiple comparisons
#' @param plotVarsICC .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$instructions} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$DESCtable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$DIFtable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$gcTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ICCplots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$instructions$asDF}
#'
#' \code{as.data.frame(results$instructions)}
#'
#' @export
glmDIF <- function(
    data,
    item,
    group,
    matchVar,
    anchor = NULL,
    focal,
    groupType,
    difFlagScale,
    designAnalysis = FALSE,
    designAnalysisSigOnly = TRUE,
    power = FALSE,
    D,
    sims = 5000,
    type = "both",
    criterion,
    alpha = 0.05,
    purify = FALSE,
    nIter = 10,
    pAdjustMethod = "BH",
    plotVarsICC) {

    if ( ! requireNamespace('jmvcore'))
        stop('glmDIF requires jmvcore to be installed (restart may be required)')

    if ( ! missing(item)) item <- jmvcore:::resolveQuo(jmvcore:::enquo(item))
    if ( ! missing(group)) group <- jmvcore:::resolveQuo(jmvcore:::enquo(group))
    if ( ! missing(matchVar)) matchVar <- jmvcore:::resolveQuo(jmvcore:::enquo(matchVar))
    if ( ! missing(anchor)) anchor <- jmvcore:::resolveQuo(jmvcore:::enquo(anchor))
    if ( ! missing(plotVarsICC)) plotVarsICC <- jmvcore:::resolveQuo(jmvcore:::enquo(plotVarsICC))
    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(item), item, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(matchVar), matchVar, NULL),
            `if`( ! missing(anchor), anchor, NULL),
            `if`( ! missing(plotVarsICC), plotVarsICC, NULL))


    options <- glmDIFOptions$new(
        item = item,
        group = group,
        matchVar = matchVar,
        anchor = anchor,
        focal = focal,
        groupType = groupType,
        difFlagScale = difFlagScale,
        designAnalysis = designAnalysis,
        designAnalysisSigOnly = designAnalysisSigOnly,
        power = power,
        D = D,
        sims = sims,
        type = type,
        criterion = criterion,
        alpha = alpha,
        purify = purify,
        nIter = nIter,
        pAdjustMethod = pAdjustMethod,
        plotVarsICC = plotVarsICC)

    results <- glmDIFResults$new(
        options = options)

    analysis <- glmDIFClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
