
# This file is automatically generated, you probably don't want to edit this

nonParametricIRTOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "nonParametricIRTOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            item = NULL,
            group = NULL,
            format = "formatMC",
            SubRank = NULL,
            miss = "option",
            NAweight = 0,
            nevalpoints = 51,
            kernel = "gaussian",
            bandwidth = "Silverman",
            RankFun = "sum",
            thetadist = "norm, 0, 1",
            itemPlotTypes = NULL,
            itemPlotSupplier = NULL,
            axistype = "score",
            itemPlotTypesDIF = NULL,
            testPlotTypesDIF = NULL,
            testPlotDensity = FALSE,
            testPlotExpected = FALSE,
            testPlotSD = FALSE, ...) {

            super$initialize(
                package='psychoPDA',
                name='nonParametricIRT',
                requiresData=TRUE,
                ...)

            private$..item <- jmvcore::OptionVariables$new(
                "item",
                item)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..format <- jmvcore::OptionList$new(
                "format",
                format,
                options=list(
                    "formatMC",
                    "formatPartial",
                    "formatNominal"),
                default="formatMC")
            private$..SubRank <- jmvcore::OptionVariable$new(
                "SubRank",
                SubRank)
            private$..miss <- jmvcore::OptionList$new(
                "miss",
                miss,
                options=list(
                    "option",
                    "random.unif",
                    "random.multinom",
                    "omit"),
                default="option")
            private$..NAweight <- jmvcore::OptionNumber$new(
                "NAweight",
                NAweight,
                min=0,
                max=1,
                default=0)
            private$..nevalpoints <- jmvcore::OptionNumber$new(
                "nevalpoints",
                nevalpoints,
                default=51)
            private$..kernel <- jmvcore::OptionList$new(
                "kernel",
                kernel,
                options=list(
                    "gaussian",
                    "quadratic",
                    "uniform"),
                default="gaussian")
            private$..bandwidth <- jmvcore::OptionList$new(
                "bandwidth",
                bandwidth,
                options=list(
                    "Silverman",
                    "CV"),
                default="Silverman")
            private$..RankFun <- jmvcore::OptionList$new(
                "RankFun",
                RankFun,
                options=list(
                    "sum",
                    "mean"),
                default="sum")
            private$..thetadist <- jmvcore::OptionString$new(
                "thetadist",
                thetadist,
                default="norm, 0, 1")
            private$..itemPlotTypes <- jmvcore::OptionList$new(
                "itemPlotTypes",
                itemPlotTypes,
                options=list(
                    "OCC",
                    "EIS"))
            private$..itemPlotSupplier <- jmvcore::OptionVariables$new(
                "itemPlotSupplier",
                itemPlotSupplier)
            private$..axistype <- jmvcore::OptionList$new(
                "axistype",
                axistype,
                options=list(
                    "distribution",
                    "score"),
                default="score")
            private$..itemPlotTypesDIF <- jmvcore::OptionList$new(
                "itemPlotTypesDIF",
                itemPlotTypesDIF,
                options=list(
                    "OCCDIF",
                    "EISDIF"))
            private$..testPlotTypesDIF <- jmvcore::OptionList$new(
                "testPlotTypesDIF",
                testPlotTypesDIF,
                options=list(
                    "densityDIF",
                    "expectedDIF"))
            private$..testPlotDensity <- jmvcore::OptionBool$new(
                "testPlotDensity",
                testPlotDensity,
                default=FALSE)
            private$..testPlotExpected <- jmvcore::OptionBool$new(
                "testPlotExpected",
                testPlotExpected,
                default=FALSE)
            private$..testPlotSD <- jmvcore::OptionBool$new(
                "testPlotSD",
                testPlotSD,
                default=FALSE)

            self$.addOption(private$..item)
            self$.addOption(private$..group)
            self$.addOption(private$..format)
            self$.addOption(private$..SubRank)
            self$.addOption(private$..miss)
            self$.addOption(private$..NAweight)
            self$.addOption(private$..nevalpoints)
            self$.addOption(private$..kernel)
            self$.addOption(private$..bandwidth)
            self$.addOption(private$..RankFun)
            self$.addOption(private$..thetadist)
            self$.addOption(private$..itemPlotTypes)
            self$.addOption(private$..itemPlotSupplier)
            self$.addOption(private$..axistype)
            self$.addOption(private$..itemPlotTypesDIF)
            self$.addOption(private$..testPlotTypesDIF)
            self$.addOption(private$..testPlotDensity)
            self$.addOption(private$..testPlotExpected)
            self$.addOption(private$..testPlotSD)
        }),
    active = list(
        item = function() private$..item$value,
        group = function() private$..group$value,
        format = function() private$..format$value,
        SubRank = function() private$..SubRank$value,
        miss = function() private$..miss$value,
        NAweight = function() private$..NAweight$value,
        nevalpoints = function() private$..nevalpoints$value,
        kernel = function() private$..kernel$value,
        bandwidth = function() private$..bandwidth$value,
        RankFun = function() private$..RankFun$value,
        thetadist = function() private$..thetadist$value,
        itemPlotTypes = function() private$..itemPlotTypes$value,
        itemPlotSupplier = function() private$..itemPlotSupplier$value,
        axistype = function() private$..axistype$value,
        itemPlotTypesDIF = function() private$..itemPlotTypesDIF$value,
        testPlotTypesDIF = function() private$..testPlotTypesDIF$value,
        testPlotDensity = function() private$..testPlotDensity$value,
        testPlotExpected = function() private$..testPlotExpected$value,
        testPlotSD = function() private$..testPlotSD$value),
    private = list(
        ..item = NA,
        ..group = NA,
        ..format = NA,
        ..SubRank = NA,
        ..miss = NA,
        ..NAweight = NA,
        ..nevalpoints = NA,
        ..kernel = NA,
        ..bandwidth = NA,
        ..RankFun = NA,
        ..thetadist = NA,
        ..itemPlotTypes = NA,
        ..itemPlotSupplier = NA,
        ..axistype = NA,
        ..itemPlotTypesDIF = NA,
        ..testPlotTypesDIF = NA,
        ..testPlotDensity = NA,
        ..testPlotExpected = NA,
        ..testPlotSD = NA)
)

nonParametricIRTResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        occPlots = function() private$.items[["occPlots"]],
        testPlotDensity = function() private$.items[["testPlotDensity"]],
        testPlotExpected = function() private$.items[["testPlotExpected"]],
        testPlotSD = function() private$.items[["testPlotSD"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Non-Parametric IRT")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                title="debug results"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Non-Parametric IRT",
                clearWith=list(
                    "item")))
            self$add(jmvcore::Array$new(
                options=options,
                name="occPlots",
                title="OCC Plots",
                items="(itemPlotSupplier)",
                template=jmvcore::Image$new(
                    options=options,
                    width=550,
                    height=450,
                    renderFun=".occPlot",
                    visible="(itemPlotSupplier)",
                    clearWith=list(
                        "item"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="testPlotDensity",
                title="Density Plot",
                visible="(testPlotDensity)",
                width=550,
                height=450,
                renderFun=".testPlotDensity",
                clearWith=list(
                    "item")))
            self$add(jmvcore::Image$new(
                options=options,
                name="testPlotExpected",
                title="Expected Plot",
                visible="(testPlotExpected)",
                width=550,
                height=450,
                renderFun=".testPlotExpected",
                clearWith=list(
                    "item")))
            self$add(jmvcore::Image$new(
                options=options,
                name="testPlotSD",
                title="SD Plot",
                visible="(testPlotSD)",
                width=550,
                height=450,
                renderFun=".testPlotSD",
                clearWith=list(
                    "item")))}))

nonParametricIRTBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "nonParametricIRTBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'psychoPDA',
                name = 'nonParametricIRT',
                version = c(1,0,0),
                options = options,
                results = nonParametricIRTResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Non-Parametric IRT
#'
#' 
#' @param data .
#' @param item .
#' @param group .
#' @param format .
#' @param SubRank .
#' @param miss .
#' @param NAweight .
#' @param nevalpoints .
#' @param kernel .
#' @param bandwidth .
#' @param RankFun .
#' @param thetadist .
#' @param itemPlotTypes .
#' @param itemPlotSupplier .
#' @param axistype .
#' @param itemPlotTypesDIF .
#' @param testPlotTypesDIF .
#' @param testPlotDensity .
#' @param testPlotExpected .
#' @param testPlotSD .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$occPlots} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$testPlotDensity} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$testPlotExpected} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$testPlotSD} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
nonParametricIRT <- function(
    data,
    item,
    group,
    format = "formatMC",
    SubRank,
    miss = "option",
    NAweight = 0,
    nevalpoints = 51,
    kernel = "gaussian",
    bandwidth = "Silverman",
    RankFun = "sum",
    thetadist = "norm, 0, 1",
    itemPlotTypes,
    itemPlotSupplier,
    axistype = "score",
    itemPlotTypesDIF,
    testPlotTypesDIF,
    testPlotDensity = FALSE,
    testPlotExpected = FALSE,
    testPlotSD = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('nonParametricIRT requires jmvcore to be installed (restart may be required)')

    if ( ! missing(item)) item <- jmvcore::resolveQuo(jmvcore::enquo(item))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(SubRank)) SubRank <- jmvcore::resolveQuo(jmvcore::enquo(SubRank))
    if ( ! missing(itemPlotSupplier)) itemPlotSupplier <- jmvcore::resolveQuo(jmvcore::enquo(itemPlotSupplier))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(item), item, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(SubRank), SubRank, NULL),
            `if`( ! missing(itemPlotSupplier), itemPlotSupplier, NULL))


    options <- nonParametricIRTOptions$new(
        item = item,
        group = group,
        format = format,
        SubRank = SubRank,
        miss = miss,
        NAweight = NAweight,
        nevalpoints = nevalpoints,
        kernel = kernel,
        bandwidth = bandwidth,
        RankFun = RankFun,
        thetadist = thetadist,
        itemPlotTypes = itemPlotTypes,
        itemPlotSupplier = itemPlotSupplier,
        axistype = axistype,
        itemPlotTypesDIF = itemPlotTypesDIF,
        testPlotTypesDIF = testPlotTypesDIF,
        testPlotDensity = testPlotDensity,
        testPlotExpected = testPlotExpected,
        testPlotSD = testPlotSD)

    analysis <- nonParametricIRTClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
