
# This file is automatically generated, you probably don't want to edit this

nonParametricIRTOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "nonParametricIRTOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            item = NULL,
            groups = NULL,
            format = "formatMC",
            SubRank = NULL,
            miss = "option",
            NAweight = 0,
            nevalpoints = 51,
            kernel = "gaussian",
            bandwidth = "Silverman",
            RankFun = "sum",
            thetadist = "norm, 0, 1",
            itemPlotTypes = NULL,
            itemPlotSupplier = NULL,
            testPlotTypes = NULL,
            itemPlotTypesDIF = NULL,
            itemPlotSupplierDIF = NULL,
            testPlotTypesDIF = NULL, ...) {

            super$initialize(
                package='psychoPDA',
                name='nonParametricIRT',
                requiresData=TRUE,
                ...)

            private$..item <- jmvcore::OptionVariables$new(
                "item",
                item)
            private$..groups <- jmvcore::OptionVariable$new(
                "groups",
                groups)
            private$..format <- jmvcore::OptionList$new(
                "format",
                format,
                options=list(
                    "formatMC",
                    "formatPartial",
                    "formatNominal"),
                default="formatMC")
            private$..SubRank <- jmvcore::OptionVariable$new(
                "SubRank",
                SubRank)
            private$..miss <- jmvcore::OptionList$new(
                "miss",
                miss,
                options=list(
                    "option",
                    "random.unif",
                    "random.multinom",
                    "omit"),
                default="option")
            private$..NAweight <- jmvcore::OptionNumber$new(
                "NAweight",
                NAweight,
                min=0,
                max=1,
                default=0)
            private$..nevalpoints <- jmvcore::OptionNumber$new(
                "nevalpoints",
                nevalpoints,
                default=51)
            private$..kernel <- jmvcore::OptionList$new(
                "kernel",
                kernel,
                options=list(
                    "gaussian",
                    "quadratic",
                    "uniform"),
                default="gaussian")
            private$..bandwidth <- jmvcore::OptionList$new(
                "bandwidth",
                bandwidth,
                options=list(
                    "Silverman",
                    "CV"),
                default="Silverman")
            private$..RankFun <- jmvcore::OptionList$new(
                "RankFun",
                RankFun,
                options=list(
                    "sum",
                    "mean"),
                default="sum")
            private$..thetadist <- jmvcore::OptionString$new(
                "thetadist",
                thetadist,
                default="norm, 0, 1")
            private$..itemPlotTypes <- jmvcore::OptionNMXList$new(
                "itemPlotTypes",
                itemPlotTypes,
                options=list(
                    "OCC",
                    "EIS"))
            private$..itemPlotSupplier <- jmvcore::OptionVariables$new(
                "itemPlotSupplier",
                itemPlotSupplier)
            private$..testPlotTypes <- jmvcore::OptionNMXList$new(
                "testPlotTypes",
                testPlotTypes,
                options=list(
                    "density",
                    "expected",
                    "sd"))
            private$..itemPlotTypesDIF <- jmvcore::OptionNMXList$new(
                "itemPlotTypesDIF",
                itemPlotTypesDIF,
                options=list(
                    "OCCDIF",
                    "EISDIF"))
            private$..itemPlotSupplierDIF <- jmvcore::OptionVariables$new(
                "itemPlotSupplierDIF",
                itemPlotSupplierDIF)
            private$..testPlotTypesDIF <- jmvcore::OptionNMXList$new(
                "testPlotTypesDIF",
                testPlotTypesDIF,
                options=list(
                    "densityDIF",
                    "expectedDIF"))

            self$.addOption(private$..item)
            self$.addOption(private$..groups)
            self$.addOption(private$..format)
            self$.addOption(private$..SubRank)
            self$.addOption(private$..miss)
            self$.addOption(private$..NAweight)
            self$.addOption(private$..nevalpoints)
            self$.addOption(private$..kernel)
            self$.addOption(private$..bandwidth)
            self$.addOption(private$..RankFun)
            self$.addOption(private$..thetadist)
            self$.addOption(private$..itemPlotTypes)
            self$.addOption(private$..itemPlotSupplier)
            self$.addOption(private$..testPlotTypes)
            self$.addOption(private$..itemPlotTypesDIF)
            self$.addOption(private$..itemPlotSupplierDIF)
            self$.addOption(private$..testPlotTypesDIF)
        }),
    active = list(
        item = function() private$..item$value,
        groups = function() private$..groups$value,
        format = function() private$..format$value,
        SubRank = function() private$..SubRank$value,
        miss = function() private$..miss$value,
        NAweight = function() private$..NAweight$value,
        nevalpoints = function() private$..nevalpoints$value,
        kernel = function() private$..kernel$value,
        bandwidth = function() private$..bandwidth$value,
        RankFun = function() private$..RankFun$value,
        thetadist = function() private$..thetadist$value,
        itemPlotTypes = function() private$..itemPlotTypes$value,
        itemPlotSupplier = function() private$..itemPlotSupplier$value,
        testPlotTypes = function() private$..testPlotTypes$value,
        itemPlotTypesDIF = function() private$..itemPlotTypesDIF$value,
        itemPlotSupplierDIF = function() private$..itemPlotSupplierDIF$value,
        testPlotTypesDIF = function() private$..testPlotTypesDIF$value),
    private = list(
        ..item = NA,
        ..groups = NA,
        ..format = NA,
        ..SubRank = NA,
        ..miss = NA,
        ..NAweight = NA,
        ..nevalpoints = NA,
        ..kernel = NA,
        ..bandwidth = NA,
        ..RankFun = NA,
        ..thetadist = NA,
        ..itemPlotTypes = NA,
        ..itemPlotSupplier = NA,
        ..testPlotTypes = NA,
        ..itemPlotTypesDIF = NA,
        ..itemPlotSupplierDIF = NA,
        ..testPlotTypesDIF = NA)
)

nonParametricIRTResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        itemPlots = function() private$.items[["itemPlots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Non-Parametric IRT")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Non-Parametric IRT"))
            self$add(jmvcore::Array$new(
                options=options,
                name="itemPlots",
                title="Item Plots",
                items="(itemPlotSupplier)",
                template=jmvcore::Image$new(
                    options=options,
                    width=550,
                    height=450,
                    renderFun=".itemPlots",
                    visible="(plotItems)",
                    requiresData=TRUE,
                    clearWith=list(
                        "item"))))}))

nonParametricIRTBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "nonParametricIRTBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'psychoPDA',
                name = 'nonParametricIRT',
                version = c(1,0,0),
                options = options,
                results = nonParametricIRTResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Non-Parametric IRT
#'
#' 
#' @param data .
#' @param item .
#' @param groups .
#' @param format .
#' @param SubRank .
#' @param miss .
#' @param NAweight .
#' @param nevalpoints .
#' @param kernel .
#' @param bandwidth .
#' @param RankFun .
#' @param thetadist .
#' @param itemPlotTypes .
#' @param itemPlotSupplier .
#' @param testPlotTypes .
#' @param itemPlotTypesDIF .
#' @param itemPlotSupplierDIF .
#' @param testPlotTypesDIF .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$itemPlots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' @export
nonParametricIRT <- function(
    data,
    item,
    groups,
    format = "formatMC",
    SubRank,
    miss = "option",
    NAweight = 0,
    nevalpoints = 51,
    kernel = "gaussian",
    bandwidth = "Silverman",
    RankFun = "sum",
    thetadist = "norm, 0, 1",
    itemPlotTypes,
    itemPlotSupplier,
    testPlotTypes,
    itemPlotTypesDIF,
    itemPlotSupplierDIF,
    testPlotTypesDIF) {

    if ( ! requireNamespace('jmvcore'))
        stop('nonParametricIRT requires jmvcore to be installed (restart may be required)')

    if ( ! missing(item)) item <- jmvcore::resolveQuo(jmvcore::enquo(item))
    if ( ! missing(groups)) groups <- jmvcore::resolveQuo(jmvcore::enquo(groups))
    if ( ! missing(SubRank)) SubRank <- jmvcore::resolveQuo(jmvcore::enquo(SubRank))
    if ( ! missing(itemPlotSupplier)) itemPlotSupplier <- jmvcore::resolveQuo(jmvcore::enquo(itemPlotSupplier))
    if ( ! missing(itemPlotSupplierDIF)) itemPlotSupplierDIF <- jmvcore::resolveQuo(jmvcore::enquo(itemPlotSupplierDIF))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(item), item, NULL),
            `if`( ! missing(groups), groups, NULL),
            `if`( ! missing(SubRank), SubRank, NULL),
            `if`( ! missing(itemPlotSupplier), itemPlotSupplier, NULL),
            `if`( ! missing(itemPlotSupplierDIF), itemPlotSupplierDIF, NULL))


    options <- nonParametricIRTOptions$new(
        item = item,
        groups = groups,
        format = format,
        SubRank = SubRank,
        miss = miss,
        NAweight = NAweight,
        nevalpoints = nevalpoints,
        kernel = kernel,
        bandwidth = bandwidth,
        RankFun = RankFun,
        thetadist = thetadist,
        itemPlotTypes = itemPlotTypes,
        itemPlotSupplier = itemPlotSupplier,
        testPlotTypes = testPlotTypes,
        itemPlotTypesDIF = itemPlotTypesDIF,
        itemPlotSupplierDIF = itemPlotSupplierDIF,
        testPlotTypesDIF = testPlotTypesDIF)

    analysis <- nonParametricIRTClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
