
# This file is automatically generated, you probably don't want to edit this

ordinalReliabilityOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ordinalReliabilityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            items = NULL,
            groups = NULL,
            alphaTable = FALSE,
            thetaTable = FALSE,
            omegaTable = FALSE,
            guttmanTable = FALSE,
            polyTable = FALSE, ...) {

            super$initialize(
                package='psychoPDA',
                name='ordinalReliability',
                requiresData=TRUE,
                ...)

            private$..items <- jmvcore::OptionVariables$new(
                "items",
                items)
            private$..groups <- jmvcore::OptionVariable$new(
                "groups",
                groups)
            private$..alphaTable <- jmvcore::OptionBool$new(
                "alphaTable",
                alphaTable,
                default=FALSE)
            private$..thetaTable <- jmvcore::OptionBool$new(
                "thetaTable",
                thetaTable,
                default=FALSE)
            private$..omegaTable <- jmvcore::OptionBool$new(
                "omegaTable",
                omegaTable,
                default=FALSE)
            private$..guttmanTable <- jmvcore::OptionBool$new(
                "guttmanTable",
                guttmanTable,
                default=FALSE)
            private$..polyTable <- jmvcore::OptionBool$new(
                "polyTable",
                polyTable,
                default=FALSE)

            self$.addOption(private$..items)
            self$.addOption(private$..groups)
            self$.addOption(private$..alphaTable)
            self$.addOption(private$..thetaTable)
            self$.addOption(private$..omegaTable)
            self$.addOption(private$..guttmanTable)
            self$.addOption(private$..polyTable)
        }),
    active = list(
        items = function() private$..items$value,
        groups = function() private$..groups$value,
        alphaTable = function() private$..alphaTable$value,
        thetaTable = function() private$..thetaTable$value,
        omegaTable = function() private$..omegaTable$value,
        guttmanTable = function() private$..guttmanTable$value,
        polyTable = function() private$..polyTable$value),
    private = list(
        ..items = NA,
        ..groups = NA,
        ..alphaTable = NA,
        ..thetaTable = NA,
        ..omegaTable = NA,
        ..guttmanTable = NA,
        ..polyTable = NA)
)

ordinalReliabilityResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        debug = function() private$.items[["debug"]],
        summaryTableAlpha = function() private$.items[["summaryTableAlpha"]],
        detailTableAlphaItemDrop = function() private$.items[["detailTableAlphaItemDrop"]],
        summaryTableGuttman = function() private$.items[["summaryTableGuttman"]],
        summaryTableOmega = function() private$.items[["summaryTableOmega"]],
        fullTableOmega = function() private$.items[["fullTableOmega"]],
        summaryTableTheta = function() private$.items[["summaryTableTheta"]],
        polychoricTable = function() private$.items[["polychoricTable"]],
        omegaDiagram = function() private$.items[["omegaDiagram"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Ordinal Reliability")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTableAlpha",
                title="Ordinal Alpha",
                visible="(alphaTable)",
                rows=1,
                columns=list(
                    list(
                        `name`="raw_alpha", 
                        `title`="raw_alpha", 
                        `type`="number"),
                    list(
                        `name`="std.alpha", 
                        `title`="std.alpha", 
                        `type`="number"),
                    list(
                        `name`="G6", 
                        `title`="G6(smc)", 
                        `type`="number"),
                    list(
                        `name`="average_r", 
                        `title`="average_r", 
                        `type`="number"),
                    list(
                        `name`="SN", 
                        `title`="SN", 
                        `type`="number"),
                    list(
                        `name`="median_r", 
                        `title`="median_r", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="detailTableAlphaItemDrop",
                title="Reliability if an item is dropped",
                visible="(alphaTable)",
                rows="(items)",
                columns=list(
                    list(
                        `name`="itemName", 
                        `title`="Item", 
                        `content`="($key)"),
                    list(
                        `name`="raw_alpha", 
                        `title`="raw_alpha", 
                        `type`="number"),
                    list(
                        `name`="std.alpha", 
                        `title`="std.alpha", 
                        `type`="number"),
                    list(
                        `name`="G6", 
                        `title`="G6(smc)", 
                        `type`="number"),
                    list(
                        `name`="average_r", 
                        `title`="average_r", 
                        `type`="number"),
                    list(
                        `name`="SN", 
                        `title`="SN", 
                        `type`="number"),
                    list(
                        `name`="var.r", 
                        `title`="var.r", 
                        `type`="number"),
                    list(
                        `name`="median_r", 
                        `title`="median_r", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTableGuttman",
                title="Ordinal Guttman",
                visible="(guttmanTable)",
                rows=1,
                columns=list(
                    list(
                        `name`="maxSHR", 
                        `title`="Max Split-Half (lambda 4)", 
                        `type`="number"),
                    list(
                        `name`="guttmanL6", 
                        `title`="Lambda 6", 
                        `type`="number"),
                    list(
                        `name`="avgSHR", 
                        `title`="Average Split-Half", 
                        `type`="number"),
                    list(
                        `name`="alpha", 
                        `title`="Alpha (lambda 3)", 
                        `type`="number"),
                    list(
                        `name`="minSHR", 
                        `title`="Min Split-Half (beta)", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTableOmega",
                title="Ordinal Omega",
                visible="(omegaTable)",
                rows=1,
                columns=list(
                    list(
                        `name`="omega_h", 
                        `title`="omega_h", 
                        `type`="number"),
                    list(
                        `name`="omega.lim", 
                        `title`="omega.lim", 
                        `type`="number"),
                    list(
                        `name`="alpha", 
                        `title`="alpha", 
                        `type`="number"),
                    list(
                        `name`="omega.tot", 
                        `title`="omega.tot", 
                        `type`="number"),
                    list(
                        `name`="G6", 
                        `title`="G6", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="fullTableOmega",
                title="Full Table Omega",
                visible="(omegaTable)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTableTheta",
                title="Ordinal Theta",
                visible="(thetaTable)",
                rows=1,
                columns=list(
                    list(
                        `name`="ordinalTheta", 
                        `title`="ordinalTheta", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="polychoricTable",
                title="Polychoric Matrix",
                visible="(polyTable)",
                rows="(items)",
                swapRowsColumns=FALSE,
                columns=list(
                    list(
                        `name`="bob", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="omegaDiagram",
                title="Ordinal Omega - Factor Model Diagram",
                visible="(omegaTable)",
                width=550,
                height=450,
                renderFun=".plotOmegaDiagram"))}))

ordinalReliabilityBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ordinalReliabilityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'psychoPDA',
                name = 'ordinalReliability',
                version = c(1,0,0),
                options = options,
                results = ordinalReliabilityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Ordinal Reliability
#'
#' 
#' @param data .
#' @param items .
#' @param groups .
#' @param alphaTable .
#' @param thetaTable .
#' @param omegaTable .
#' @param guttmanTable .
#' @param polyTable .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summaryTableAlpha} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$detailTableAlphaItemDrop} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryTableGuttman} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryTableOmega} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fullTableOmega} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summaryTableTheta} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$polychoricTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$omegaDiagram} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summaryTableAlpha$asDF}
#'
#' \code{as.data.frame(results$summaryTableAlpha)}
#'
#' @export
ordinalReliability <- function(
    data,
    items,
    groups,
    alphaTable = FALSE,
    thetaTable = FALSE,
    omegaTable = FALSE,
    guttmanTable = FALSE,
    polyTable = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('ordinalReliability requires jmvcore to be installed (restart may be required)')

    if ( ! missing(items)) items <- jmvcore::resolveQuo(jmvcore::enquo(items))
    if ( ! missing(groups)) groups <- jmvcore::resolveQuo(jmvcore::enquo(groups))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(items), items, NULL),
            `if`( ! missing(groups), groups, NULL))


    options <- ordinalReliabilityOptions$new(
        items = items,
        groups = groups,
        alphaTable = alphaTable,
        thetaTable = thetaTable,
        omegaTable = omegaTable,
        guttmanTable = guttmanTable,
        polyTable = polyTable)

    results <- ordinalReliabilityResults$new(
        options = options)

    analysis <- ordinalReliabilityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
