
# This file is automatically generated, you probably don't want to edit this

ttestCorOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ttestCorOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labelVar = NULL,
            hypTrueCor = NULL,
            observedSE = NULL,
            observedCor = NULL,
            n = NULL,
            nullCor = 0,
            alpha = 0.05,
            nSims = 10000, ...) {

            super$initialize(
                package='DIF',
                name='ttestCor',
                requiresData=TRUE,
                ...)

            private$..labelVar <- jmvcore::OptionVariable$new(
                "labelVar",
                labelVar,
                suggested=list(
                    "nominal"))
            private$..hypTrueCor <- jmvcore::OptionVariable$new(
                "hypTrueCor",
                hypTrueCor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..observedSE <- jmvcore::OptionVariable$new(
                "observedSE",
                observedSE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..observedCor <- jmvcore::OptionVariable$new(
                "observedCor",
                observedCor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..n <- jmvcore::OptionVariable$new(
                "n",
                n,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nullCor <- jmvcore::OptionNumber$new(
                "nullCor",
                nullCor,
                default=0)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..nSims <- jmvcore::OptionNumber$new(
                "nSims",
                nSims,
                default=10000)

            self$.addOption(private$..labelVar)
            self$.addOption(private$..hypTrueCor)
            self$.addOption(private$..observedSE)
            self$.addOption(private$..observedCor)
            self$.addOption(private$..n)
            self$.addOption(private$..nullCor)
            self$.addOption(private$..alpha)
            self$.addOption(private$..nSims)
        }),
    active = list(
        labelVar = function() private$..labelVar$value,
        hypTrueCor = function() private$..hypTrueCor$value,
        observedSE = function() private$..observedSE$value,
        observedCor = function() private$..observedCor$value,
        n = function() private$..n$value,
        nullCor = function() private$..nullCor$value,
        alpha = function() private$..alpha$value,
        nSims = function() private$..nSims$value),
    private = list(
        ..labelVar = NA,
        ..hypTrueCor = NA,
        ..observedSE = NA,
        ..observedCor = NA,
        ..n = NA,
        ..nullCor = NA,
        ..alpha = NA,
        ..nSims = NA)
)

ttestCorResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        rdTTestCor = function() private$.items[["rdTTestCor"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="T-Test for Correlations")
            self$add(jmvcore::Table$new(
                options=options,
                name="rdTTestCor",
                title="Retroactive Design Analysis | T-Test for Correlations",
                rows=0,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Label", 
                        `type`="text"),
                    list(
                        `name`="hypTrueCorLabel", 
                        `title`="Hypothesized True Correlation", 
                        `type`="number"),
                    list(
                        `name`="typeS", 
                        `title`="Type-S", 
                        `type`="number"),
                    list(
                        `name`="typeM", 
                        `title`="Type-M", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Observed Power", 
                        `type`="number"))))}))

ttestCorBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ttestCorBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'DIF',
                name = 'ttestCor',
                version = c(1,0,0),
                options = options,
                results = ttestCorResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Correlations
#'
#' 
#' @param data .
#' @param labelVar .
#' @param hypTrueCor .
#' @param observedSE .
#' @param observedCor .
#' @param n .
#' @param nullCor .
#' @param alpha .
#' @param nSims .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$rdTTestCor} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$rdTTestCor$asDF}
#'
#' \code{as.data.frame(results$rdTTestCor)}
#'
#' @export
ttestCor <- function(
    data,
    labelVar,
    hypTrueCor,
    observedSE,
    observedCor,
    n,
    nullCor = 0,
    alpha = 0.05,
    nSims = 10000) {

    if ( ! requireNamespace('jmvcore'))
        stop('ttestCor requires jmvcore to be installed (restart may be required)')

    if ( ! missing(labelVar)) labelVar <- jmvcore:::resolveQuo(jmvcore:::enquo(labelVar))
    if ( ! missing(hypTrueCor)) hypTrueCor <- jmvcore:::resolveQuo(jmvcore:::enquo(hypTrueCor))
    if ( ! missing(observedSE)) observedSE <- jmvcore:::resolveQuo(jmvcore:::enquo(observedSE))
    if ( ! missing(observedCor)) observedCor <- jmvcore:::resolveQuo(jmvcore:::enquo(observedCor))
    if ( ! missing(n)) n <- jmvcore:::resolveQuo(jmvcore:::enquo(n))
    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(labelVar), labelVar, NULL),
            `if`( ! missing(hypTrueCor), hypTrueCor, NULL),
            `if`( ! missing(observedSE), observedSE, NULL),
            `if`( ! missing(observedCor), observedCor, NULL),
            `if`( ! missing(n), n, NULL))


    options <- ttestCorOptions$new(
        labelVar = labelVar,
        hypTrueCor = hypTrueCor,
        observedSE = observedSE,
        observedCor = observedCor,
        n = n,
        nullCor = nullCor,
        alpha = alpha,
        nSims = nSims)

    results <- ttestCorResults$new(
        options = options)

    analysis <- ttestCorClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
