
# This file is automatically generated, you probably don't want to edit this

ttestCorOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ttestCorOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labelVar = NULL,
            hypTrueCor = NULL,
            observedSE = NULL,
            observedCor = NULL,
            n = NULL,
            alpha = 0.05,
            sensHyp = TRUE,
            sensN = TRUE, ...) {

            super$initialize(
                package='psychoPDA',
                name='ttestCor',
                requiresData=TRUE,
                ...)

            private$..labelVar <- jmvcore::OptionVariable$new(
                "labelVar",
                labelVar,
                suggested=list(
                    "nominal"))
            private$..hypTrueCor <- jmvcore::OptionVariable$new(
                "hypTrueCor",
                hypTrueCor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..observedSE <- jmvcore::OptionVariable$new(
                "observedSE",
                observedSE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..observedCor <- jmvcore::OptionVariable$new(
                "observedCor",
                observedCor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..n <- jmvcore::OptionVariable$new(
                "n",
                n,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..sensHyp <- jmvcore::OptionBool$new(
                "sensHyp",
                sensHyp,
                default=TRUE)
            private$..sensN <- jmvcore::OptionBool$new(
                "sensN",
                sensN,
                default=TRUE)

            self$.addOption(private$..labelVar)
            self$.addOption(private$..hypTrueCor)
            self$.addOption(private$..observedSE)
            self$.addOption(private$..observedCor)
            self$.addOption(private$..n)
            self$.addOption(private$..alpha)
            self$.addOption(private$..sensHyp)
            self$.addOption(private$..sensN)
        }),
    active = list(
        labelVar = function() private$..labelVar$value,
        hypTrueCor = function() private$..hypTrueCor$value,
        observedSE = function() private$..observedSE$value,
        observedCor = function() private$..observedCor$value,
        n = function() private$..n$value,
        alpha = function() private$..alpha$value,
        sensHyp = function() private$..sensHyp$value,
        sensN = function() private$..sensN$value),
    private = list(
        ..labelVar = NA,
        ..hypTrueCor = NA,
        ..observedSE = NA,
        ..observedCor = NA,
        ..n = NA,
        ..alpha = NA,
        ..sensHyp = NA,
        ..sensN = NA)
)

ttestCorResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        instructions = function() private$.items[["instructions"]],
        rdTTestCor = function() private$.items[["rdTTestCor"]],
        plotHTE = function() private$.items[["plotHTE"]],
        plotN = function() private$.items[["plotN"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="T-Test for Correlations")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                title="debug"))
            self$add(jmvcore::Table$new(
                options=options,
                name="instructions",
                title="Instructions",
                rows=4,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="frank", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rdTTestCor",
                title="Retroactive Design Analysis | Correlations",
                rows=0,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Label", 
                        `type`="text"),
                    list(
                        `name`="obsCor", 
                        `title`="Obs. Correlation", 
                        `type`="number"),
                    list(
                        `name`="obsN", 
                        `title`="N", 
                        `type`="number"),
                    list(
                        `name`="hypTrueCor", 
                        `title`="Hyp. True Correlation", 
                        `type`="number"),
                    list(
                        `name`="obsSE", 
                        `title`="Obs. SE", 
                        `type`="number"),
                    list(
                        `name`="hypTrueEffSD", 
                        `title`="D", 
                        `type`="number"),
                    list(
                        `name`="typeS", 
                        `title`="Type-S", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="typeM", 
                        `title`="Type-M", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Emp. Obs. Power", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotHTE",
                title="Sensitivity - Hypothesized True Effect",
                visible="(sensHyp)",
                width=800,
                height=600,
                renderFun=".plotHTE"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotN",
                title="Sensitivity - Sample Size",
                visible="(sensN)",
                width=800,
                height=600,
                renderFun=".plotN"))}))

ttestCorBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ttestCorBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'psychoPDA',
                name = 'ttestCor',
                version = c(1,0,0),
                options = options,
                results = ttestCorResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Correlations
#'
#' 
#' @param data .
#' @param labelVar .
#' @param hypTrueCor .
#' @param observedSE .
#' @param observedCor .
#' @param n .
#' @param alpha .
#' @param sensHyp .
#' @param sensN .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$instructions} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rdTTestCor} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotHTE} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotN} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$instructions$asDF}
#'
#' \code{as.data.frame(results$instructions)}
#'
#' @export
ttestCor <- function(
    data,
    labelVar,
    hypTrueCor,
    observedSE,
    observedCor,
    n,
    alpha = 0.05,
    sensHyp = TRUE,
    sensN = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('ttestCor requires jmvcore to be installed (restart may be required)')

    if ( ! missing(labelVar)) labelVar <- jmvcore::resolveQuo(jmvcore::enquo(labelVar))
    if ( ! missing(hypTrueCor)) hypTrueCor <- jmvcore::resolveQuo(jmvcore::enquo(hypTrueCor))
    if ( ! missing(observedSE)) observedSE <- jmvcore::resolveQuo(jmvcore::enquo(observedSE))
    if ( ! missing(observedCor)) observedCor <- jmvcore::resolveQuo(jmvcore::enquo(observedCor))
    if ( ! missing(n)) n <- jmvcore::resolveQuo(jmvcore::enquo(n))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labelVar), labelVar, NULL),
            `if`( ! missing(hypTrueCor), hypTrueCor, NULL),
            `if`( ! missing(observedSE), observedSE, NULL),
            `if`( ! missing(observedCor), observedCor, NULL),
            `if`( ! missing(n), n, NULL))


    options <- ttestCorOptions$new(
        labelVar = labelVar,
        hypTrueCor = hypTrueCor,
        observedSE = observedSE,
        observedCor = observedCor,
        n = n,
        alpha = alpha,
        sensHyp = sensHyp,
        sensN = sensN)

    results <- ttestCorResults$new(
        options = options)

    analysis <- ttestCorClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
